name: m_one_task
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  freezed: ^2.5.8
  dart_extensions: ^2.2.4
  intl: ^0.19.0
  intl_utils: ^2.8.11
  dio: ^5.8.0+1
  go_router: ^16.0.0
  injectable: ^2.5.0
  shared_preferences: ^2.5.3
  get_it: ^8.0.3
  flutter_gen: ^5.10.0
  logger: ^2.6.0
  provider: ^6.1.5
  responsive_framework: ^0.2.0
  flutter_screenutil: ^5.9.3
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.14
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.4
  mobx_codegen: ^2.7.1
 
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  generate: true
 
